/* eslint-disable @next/next/no-page-custom-font */
import "@/app/globals.css";
import "@/app/styles/component.css";
import Footer from "@/components/theme-configs/footer/Footer";
import Header from "@/components/theme-configs/header/Header";
import { getThemeConfig } from "@/lib/api";
import { getFontUrl, convertCssVariables } from "@/lib/utils";
import { find, unescape } from "lodash";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {
    data,
    data: {
      object_config: {
        root,
        header,
        theme_settings: { children_items },
      },
    },
  } = await getThemeConfig();

  const color = find(children_items, { id: "color" }).settings;

  const typographyConfig = find(children_items, {
    id: "typography",
  }).children_items;

  const {
    settings: { font_url },
  } = find(children_items, {
    id: "typography",
  });

  const headingStyle = find(typographyConfig, {
    id: "style_heading",
  }).settings;

  const bodyStyle = find(typographyConfig, { id: "style_body" }).settings;

  const btnNLinkStyle = find(typographyConfig, {
    id: "style_button_link",
  }).settings;

  console.log(header);
  

  return (
    <html lang="en" suppressHydrationWarning className="text-base font-body">
      <head>
        <link href={getFontUrl(font_url.value) ?? ""} rel="stylesheet" />
      </head>
      <body>
        <style
          dangerouslySetInnerHTML={{ __html: convertCssVariables(root) }}
        ></style>
        <style>{`
        :root {
         --color-primary: ${color.primary_color.value};
          --heading-text-color: ${color.heading_text_color.value};
          --body-text-color: ${color.body_text_color.value};
          --button-text-color: ${color.button_text_color.value};
          --button-background-color: ${color.button_color.value};
          --button-background-color-hover: ${color.button_color_hover.value};

          --font-family-heading: ${unescape(headingStyle.font_family.value)};
          --font-size-heading: ${headingStyle.font_base_size.value}px;
          --font-variant-heading: ${headingStyle.font_variant.value};

          --font-family-body: ${unescape(bodyStyle.font_family.value)};
          --font-size-body: ${bodyStyle.font_base_size.value}px;
          --font-variant-body: ${bodyStyle.font_variant.value};

          --font-family-button-link: ${btnNLinkStyle.font_family.value};
          --font-size-button-link: ${btnNLinkStyle.font_base_size.value}px;
          --font-variant-button-link: ${btnNLinkStyle.font_variant.value};
        }
        `}</style>
        <Header {...header} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
