import Announcement from "@/components/theme-configs/announcement/Announcement";
import Header from "@/components/theme-configs/header/Header";
import "@/app/globals.css";
import Footer from "@/components/theme-configs/footer/Footer";
import { getThemeConfig } from "@/lib/api";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const {
  //   data,
  //   data: {
  //     object_config: { root },
  //   },
  // } = await getThemeConfig();

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Announcement />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
